# Generated by Django 6.0.2 on 2026-05-10 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active month will show on website')),
            ],
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(default='Coach', max_length=100)),
                ('photo', models.ImageField(upload_to='coaches/')),
                ('bio', models.TextField(blank=True)),
                ('clients', models.IntegerField(default=0)),
                ('years', models.IntegerField(default=0)),
                ('consultations', models.IntegerField(default=0)),
                ('specialization', models.CharField(max_length=100)),
                ('specializations', models.TextField(blank=True, help_text='Comma separated values. Example: Weight Loss, Muscle Gain')),
                ('credentials', models.TextField(blank=True, help_text='Comma separated values. Example: NASM Certified, Herbalife Coach')),
                ('is_head_coach', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, max_length=50)),
                ('link', models.URLField(blank=True, help_text='Optional link (Zoom, WhatsApp, registration, etc.)')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('event', 'Event'), ('trip', 'Trip'), ('lifestyle', 'Lifestyle'), ('transformation', 'Transformation')], default='lifestyle', max_length=30)),
                ('caption', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover_photo', models.ImageField(upload_to='gallery/covers/')),
                ('category', models.CharField(choices=[('event', 'Event'), ('trip', 'Trip'), ('lifestyle', 'Lifestyle'), ('community', 'Community')], default='lifestyle', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('goal', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='programs/')),
                ('features', models.TextField(blank=True, help_text='Enter one feature per line')),
            ],
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Shreyas Wellness World', max_length=120)),
                ('short_name', models.CharField(default='Shreyas Wellness', max_length=80)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quote', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('video', models.FileField(blank=True, null=True, upload_to='reels/')),
                ('journey_url', models.URLField(blank=True, help_text='Link to full transformation story', null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('show_on_homepage', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, help_text='Example: 7:00 AM – Yoga Session', max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.calendarmonth')),
            ],
        ),
        migrations.CreateModel(
            name='GallerySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/sections/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.gallerystory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery/photos/')),
                ('video', models.FileField(blank=True, help_text='MP4 only (optional)', null=True, upload_to='gallery/videos/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='website.gallerystory')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('before_photo', models.ImageField(upload_to='transformations/')),
                ('after_photo', models.ImageField(upload_to='transformations/')),
                ('result_text', models.CharField(help_text='Example: -12 kg, +8 kg muscle, -15% body fat', max_length=100)),
                ('short_story', models.TextField(help_text='Short testimonial shown on grid')),
                ('full_story', models.TextField(help_text='Full journey text')),
                ('category', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('wellness', 'Lifestyle / Wellness')], default='weight_loss', max_length=50)),
                ('duration', models.CharField(blank=True, help_text='Example: 12 weeks, 6 months', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.coach')),
            ],
        ),
        migrations.CreateModel(
            name='JourneySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='journey_sections/')),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.transformation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TransformationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='website.transformation')),
            ],
        ),
    ]
