# Generated by Django 6.0.2 on 2026-02-13 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='is_head_coach',
            field=models.BooleanField(default=False),
        ),
    ]
