# Generated by Django 6.0.2 on 2026-02-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_coach_is_head_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='features',
            field=models.TextField(blank=True, help_text='Enter one feature per line'),
        ),
    ]
