# Generated by Django 6.0.2 on 2026-02-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_program_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='journey_url',
            field=models.URLField(blank=True, help_text='Link to full transformation story', null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='reels/'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='quote',
            field=models.TextField(blank=True),
        ),
    ]
