# Generated by Django 6.0.2 on 2026-02-13 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_testimonial_journey_url_testimonial_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='show_on_homepage',
            field=models.BooleanField(default=True),
        ),
    ]
