# Generated by Django 6.0.2 on 2026-02-13 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_testimonial_is_featured_testimonial_show_on_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='goal',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
