# Generated by Django 6.0.2 on 2026-02-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_appointment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
