# Generated by Django 6.0.2 on 2026-02-14 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_delete_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='specialization',
            field=models.CharField(default='General Wellness', max_length=100),
            preserve_default=False,
        ),
    ]
