# Generated by Django 6.0.2 on 2026-02-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_coach_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
