# Generated by Django 6.0.2 on 2026-02-14 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_coach_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='credentials',
            field=models.TextField(blank=True, help_text='Comma separated values. Example: NASM Certified, Herbalife Coach'),
        ),
        migrations.AddField(
            model_name='coach',
            name='specializations',
            field=models.TextField(blank=True, help_text='Comma separated values. Example: Weight Loss, Muscle Gain'),
        ),
    ]
