# Generated by Django 6.0.2 on 2026-02-14 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_coach_credentials_coach_specializations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('before_photo', models.ImageField(upload_to='transformations/')),
                ('after_photo', models.ImageField(upload_to='transformations/')),
                ('result_text', models.CharField(help_text='Example: -12 kg, +8 kg muscle, -15% body fat', max_length=100)),
                ('short_story', models.TextField(help_text='Short testimonial shown on grid')),
                ('full_story', models.TextField(help_text='Full journey text')),
                ('category', models.CharField(choices=[('weight_loss', 'Weight Loss'), ('muscle_gain', 'Muscle Gain'), ('wellness', 'Lifestyle / Wellness')], default='weight_loss', max_length=50)),
                ('duration', models.CharField(blank=True, help_text='Example: 12 weeks, 6 months', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.coach')),
            ],
        ),
        migrations.CreateModel(
            name='JourneySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='website.transformation')),
            ],
        ),
        migrations.CreateModel(
            name='TransformationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=50)),
                ('transformation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='website.transformation')),
            ],
        ),
    ]
