# Generated by Django 6.0.2 on 2026-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_transformation_journeysection_transformationmetric'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journeysection',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='journeysection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journey_sections/'),
        ),
        migrations.AddField(
            model_name='journeysection',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
