# Generated by Django 6.0.2 on 2026-02-14 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_journeysection_options_journeysection_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='gallery/')),
                ('category', models.CharField(choices=[('event', 'Event'), ('trip', 'Trip'), ('lifestyle', 'Lifestyle'), ('transformation', 'Transformation')], default='lifestyle', max_length=30)),
                ('caption', models.TextField(blank=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
