# Generated by Django 6.0.2 on 2026-02-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_gallerystory_gallerysection_galleryphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='video',
            field=models.FileField(blank=True, help_text='MP4 only (optional)', null=True, upload_to='gallery/videos/'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/photos/'),
        ),
    ]
