# Generated by Django 6.0.2 on 2026-02-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_galleryphoto_video_alter_galleryphoto_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarMonth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only one active month will show on website')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('time', models.CharField(blank=True, help_text='Example: 7:00 AM – Yoga Session', max_length=50)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='website.calendarmonth')),
            ],
        ),
    ]
