# Generated by Django 6.0.2 on 2026-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(blank=True, help_text='Optional link (Zoom, WhatsApp, registration, etc.)'),
        ),
    ]
