# Generated by Django 6.0.2 on 2026-02-15 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0019_event_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
