# Generated by Django 6.0.2 on 2026-02-15 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(help_text='Primary identifier for coach', max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('parent_coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline_coaches', to='tracking.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('start_date', models.DateField()),
                ('dob', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='tracking.coach')),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyCheckin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('weight', models.FloatField(help_text='Kg')),
                ('body_fat_percent', models.FloatField(help_text='%')),
                ('body_fluid_percent', models.FloatField(help_text='%')),
                ('muscle_mass_percent', models.FloatField(help_text='%')),
                ('fat_kg', models.FloatField(blank=True, null=True)),
                ('excess_body_fluid', models.FloatField(blank=True, help_text='Water reduced per day (grams)', null=True)),
                ('notes', models.TextField(blank=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='tracking.client')),
            ],
        ),
    ]
