# Generated by Django 6.0.2 on 2026-02-15 16:13

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='client',
        ),
        migrations.RemoveField(
            model_name='coach',
            name='parent_coach',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='checkin_date',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='excess_body_fluid',
        ),
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='muscle_mass_percent',
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='date',
            field=models.DateField(default=datetime.date(2026, 2, 15)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='excess_fluid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklycheckin',
            name='body_fat_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklycheckin',
            name='body_fluid_percent',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='weeklycheckin',
            name='weight',
            field=models.FloatField(help_text='Weight in kg'),
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('role', models.CharField(choices=[('client', 'Client'), ('coach', 'Coach')], default='client', max_length=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downline', to='tracking.person')),
            ],
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='tracking.person'),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Coach',
        ),
    ]
