# Generated by Django 6.0.2 on 2026-02-15 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_remove_weeklycheckin_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklycheckin',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='tracking.person'),
        ),
    ]
