# Generated by Django 6.0.2 on 2026-02-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_alter_weeklycheckin_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklycheckin',
            name='fat_kg',
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='bma',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='body_fat_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='muscle_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='rmr',
            field=models.FloatField(blank=True, help_text='Resting Metabolic Rate', null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='subcutaneous_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='trunk_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklycheckin',
            name='visceral_fat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklycheckin',
            name='body_fluid_percent',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
