# Generated by Django 6.0.2 on 2026-02-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_remove_weeklycheckin_fat_kg_weeklycheckin_bma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='height_cm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
