# Generated by Django 6.0.2 on 2026-02-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_person_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='goal',
            field=models.CharField(blank=True, choices=[('weight_loss', 'Weight Loss'), ('weight_gain', 'Weight Gain'), ('muscle_gain', 'Muscle Gain'), ('fat_loss', 'Fat Loss'), ('maintenance', 'Maintenance')], max_length=20, null=True),
        ),
    ]
